.TH MYSTRCAT 3 "September 23, 2025" "libmyutils" "Library Functions"
.SH NAME
mystrcat \- concatenate two strings
.SH SYNOPSIS
.B int mystrcat(char *dest, const char *src);
.SH DESCRIPTION
The mystrcat() function appends the string pointed to by src to the end
of the string pointed to by dest. The dest buffer must be large enough
to hold the resulting combined string including the terminating null.
.SH AUTHOR
Your Taha <tahasaleem981@gmail.com>
