.TH MYSTRLEN 3 "September 23, 2025" "libmyutils" "Library Functions"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B int mystrlen(const char *s);
.SH DESCRIPTION
The mystrlen() function returns the number of characters in the string
pointed to by s, excluding the terminating null byte ('\0').
.SH AUTHOR
Your Taha <tahasaleem981@gmail.com>
